# ai_agent_project/docker-compose.yml

version: "3.8"
services:
  backend:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  frontend:
    build: .
    command: streamlit run ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
